# This file defines charm config options, and populates the Configure tab on Charmhub.
# If your charm does not require configuration options, delete this file entirely.
#
# See https://juju.is/docs/config for guidance.

options:
  rpc-endpoint-api-url:
    description: |
      The URL to the Flask app serving the RPC endpoint database.
    default: http://localhost:5000
    type: string
  rpc-endpoint-cache-age:
    description: |
      The maximum length in seconds to use the cached RPC endpoint values before attempting an update.
    default: 60
    type: int
  request-interval:
    description: |
      The organization name used when setting up InfluxDB.
    default: 10
    type: int

  # InfluxDB settings
  influxdb-url:
    description: |
      The URL to the InfluxDB database where blockchain request results will be stored.
    default: http://localhost:8086
    type: string
  influxdb-org:
    description: |
      The organization name used when setting up InfluxDB.
      Note: required setting when deploying the charm!
    default: ""
    type: string
  influxdb-bucket:
    description: |
      The bucket name used when setting up InfluxDB.
      Note: required setting when deploying the charm!
    default: ""
    type: string
