# This file defines charm config options, and populates the Configure tab on Charmhub.
# If your charm does not require configuration options, delete this file entirely.
#
# See https://juju.is/docs/config for guidance.

options:
  rpc-endpoint-api-url:
    description: |
      The URL to the Flask app serving the RPC endpoint database.
    default: http://localhost:5000
    type: string
  rpc-endpoint-cache-age:
    description: |
      The maximum length in seconds to use the cached RPC endpoint values before attempting an update.
    default: 60
    type: int
  request-interval:
    description: |
      The organization name used when setting up InfluxDB.
    default: 10
    type: int

  # InfluxDB settings
  influxdb-url:
    description: |
      The URL to the InfluxDB database where blockchain request results will be stored.
    default: http://localhost:8086
    type: string
  influxdb-bucket:
    description: |
      The bucket name used when setting up InfluxDB.
      Note: supplying this is required when deploying the charm!
    default: ""
    type: string
  influxdb-org:
    description: |
      The organization name used when setting up InfluxDB.
      Note: supplying this is required when deploying the charm!
    default: ""
    type: string
  # Only used at deploy, if changes are needed later they will have to be done manually
  influxdb-username:
    description: |
      The username used when setting up InfluxDB.
    default: admin
    type: string
  influxdb-password:
    description: |
      The password used when setting up InfluxDB.
    default: password
    type: string
  influxdb-retention:
    description: |
      The retention period for data in the database. Valid units: minutes (m), hours (h), days (d), and weeks (w).
    default: 30d
    type: string
